import gigadao_logo from "../img/dao-images/GigsTokenImage_black_background.png";
import {Dao} from "../pic/pic";

let verifiedDaos: Array<Dao> = [
    {
        display_name: "GigaDAO",
        dao_id: "gigadao",
        num_nfts: 1313,
        image_url: gigadao_logo,
        is_member: false,
        address: undefined,
    },
    {
        display_name: "FatDAO",
        dao_id: "fatdao",
        num_nfts: 1313,
        image_url: "https://img.tek.id/img/content/2022/01/13/48401/apa-itu-nft-panduan-bagi-para-pemula-u4YJMBAzza.jpg",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "TallDAO",
        dao_id: "talldao",
        num_nfts: 1313,
        image_url: "https://upload.wikimedia.org/wikipedia/commons/1/14/Chimp_Brain_in_a_jar.jpg",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "KaijurebornDAO",
        dao_id: "kaijureborn",
        num_nfts: 1313,
        image_url: "https://arweave.net/RdktCi3LBIj64SzC3OrGZYmlc2_EVdW80hdnbNL2uho?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "ApesbvipclubDAO",
        dao_id: "apesbvipclub",
        num_nfts: 205,
        image_url: "https://monkelabs.nyc3.digitaloceanspaces.com/apes-vip-club/images/dada2b28ca0534e8fe58f2556f515df9.png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SpacerunnersDAO",
        dao_id: "spacerunners",
        num_nfts: 10000,
        image_url: "https://metadata-temp-api.spacerunners.com/images/4507",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "BokungeckosDAO",
        dao_id: "bokungeckos",
        num_nfts: 394,
        image_url: "https://arweave.net/Vn4uFPtsbKGsR8Dtr5L-ANPbDYoUSdEyv1VBTtG02EI?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "NonanasolanaDAO",
        dao_id: "nonanasolana",
        num_nfts: 2072,
        image_url: "https://www.arweave.net/lgoDCGwvF5XSfeAFv9XBiocagVBtDX72XiJYHjUZLKg?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "DillthesealDAO",
        dao_id: "dilltheseal",
        num_nfts: 6666,
        image_url: "https://www.arweave.net/ujgXSC3_25ZheW0krjZkqMO_N4DvuiuCzPWWLeFVC04?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SkellygangnftDAO",
        dao_id: "skellygangnft",
        num_nfts: 666,
        image_url: "https://arweave.net/FtKzC71b8cwOOeQ36_tWeTAaQn409UBvrt2gPzzokas",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "ThugmoknkezDAO",
        dao_id: "thugmoknkez",
        num_nfts: 3333,
        image_url: "https://arweave.net/Vilxm7qp5RadKazRXml3vGJyrLoGr8h9NuUsoN1Eiqk?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SolanamonkerejectsDAO",
        dao_id: "solanamonkerejects",
        num_nfts: 5991,
        image_url: "https://d1g1xztyt00aex.cloudfront.net/assets/4987.png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "MoshiheadsDAO",
        dao_id: "moshiheads",
        num_nfts: 3000,
        image_url: "https://monkelabs.nyc3.digitaloceanspaces.com/moshiheads/images/29d7fa7f1e01e0d3c302fbbb897b1c67.png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "PortalscitizencardsDAO",
        dao_id: "portalscitizencards",
        num_nfts: 5000,
        image_url: "https://ipfs.io/ipfs/Qmd31K7on1bcfut9Dd7oabWkmZ4DXod4MAsQkoi7mKM72V",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "bullandbearsDAO",
        dao_id: "bullandbears",
        num_nfts: 2500,
        image_url: "https://prodbnbnft.s3.us-east-2.amazonaws.com/1233.png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SoulkombatdragonsDAO",
        dao_id: "soulkombatdragons",
        num_nfts: 1000,
        image_url: "https://www.arweave.net/XYrm_IQbNcJqhOHub5cNKmBUfTUS1Qsb7MtLnlRtLa0?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SolanamoneyboysDAO",
        dao_id: "solanamoneyboys",
        num_nfts: 1111,
        image_url: "https://www.arweave.net/bnn2haKQuaCvykltEx6HcRjU4pFj8BNP6Td-2XZKSvU?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "AlphagorillasDAO",
        dao_id: "alphagorillas",
        num_nfts: 5000,
        image_url: "https://bafybeibdvuw2c5z44zwmpcf2i4cteteb55fwhjp6isttta2tqraepgo5ti.ipfs.dweb.link/1335.png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SoullesspetsDAO",
        dao_id: "soullesspets",
        num_nfts: 2657,
        image_url: "https://www.arweave.net/DmuvJO8q9j2ArvTXft-TTAcqmszZq6NN11b_usahatA?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "Pixelracersgen1DAO",
        dao_id: "pixelracersgen1",
        num_nfts: 10000,
        image_url: "https://www.arweave.net/9DbjAXhVDE1wyrTUHDz8wjfwW4wb-R-AnURKulAeU44",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "Pixelracersgen1pitcrewDAO",
        dao_id: "pixelracersgen1pitcrew",
        num_nfts: 100,
        image_url: "https://www.arweave.net/AQ33xPgqBIRmIULlvPFDUMWc9VhOfqIthwo6zagebHI",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "RoyalepandasclubDAO",
        dao_id: "royalepandasclub",
        num_nfts: 7777,
        image_url: "https://royalepandas.mypinata.cloud/ipfs/QmV5jj34H3cFG62wmNTU9Ra5WU3v4utceBpiXYVABVp3M2/4492.png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SoltreezDAO",
        dao_id: "soltreez",
        num_nfts: 4465,
        image_url: "https://www.arweave.net/iFafdLHGAuAU5oerwigTETqRVgOB1oxtauUTkxc0aIY?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "BotheredottersgoldenticketsDAO",
        dao_id: "botheredottersgoldentickets",
        num_nfts: 8888,
        image_url: "https://www.arweave.net/5upxKk9N5hRsUhdPuaF-INFVIeRVG-IbuHYbsfNDp5w?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "888anonclubDAO",
        dao_id: "888anonclub",
        num_nfts: 888,
        image_url: "https://www.arweave.net/izBHXDrXWDl4Tu8-afeywfd6-sAQ8LUKU8LVkqiZ5jo?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "CryptografDAO",
        dao_id: "cryptograf",
        num_nfts: 5545,
        image_url: "https://arweave.net/7UKT2XIrd3bj89ZkBcl55myYUwJ6HkkZ0p9keKHb_Sg",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "WabbitsDAO",
        dao_id: "wabbits",
        num_nfts: 2222,
        image_url: "https://www.arweave.net/4btBJpN474_El52A1TR1wmawm2RZmaRtKAABxT09B4I?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "0euvrefristgenDAO",
        dao_id: "0euvrefristgen",
        num_nfts: 74,
        image_url: "https://www.arweave.net/mui-LvWKc0OEgG1UeOcwkUVcsnKbgnoEWHhBA3Y-DmE?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SlumcatDAO",
        dao_id: "slumcat",
        num_nfts: 1621,
        image_url: "https://www.arweave.net/hdVMsck4JXcKByNPhP94K49qjeKYRoQbxsrVGQ3X07Y?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "Pixelracersgen1enginesDAO",
        dao_id: "pixelracersgen1engines",
        num_nfts: 2828,
        image_url: "https://www.arweave.net/k6fmVFdrF2ICrvz7aUKL8ChQshm2GAimurEEWARKYdc",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "BossbullsclubDAO",
        dao_id: "bossbullsclub",
        num_nfts: 9999,
        image_url: "https://www.arweave.net/3kYkiUV1vE1m4TS8ClbGDug9LBoYWvP4BRxEDbEmQjA?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SolcapysDAO",
        dao_id: "solcapys",
        num_nfts: 3333,
        image_url: "https://www.arweave.net/ICYlyFQxOzBFqCUmURdx2ohb8OYfEIKuT5t91MpUGtw?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "TheinfungiblesDAO",
        dao_id: "theinfungibles",
        num_nfts: 7777,
        image_url: "https://infungibles.io/si/4050.png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "CyborgiguanasDAO",
        dao_id: "cyborgiguanas",
        num_nfts: 2222,
        image_url: "https://www.arweave.net/wQFBvdOXucmTcijVfbbsQS1u5D2UWglrO1bIv92RnXA?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "BelugieDAO",
        dao_id: "belugie",
        num_nfts: 8000,
        image_url: "https://www.arweave.net/G_7svbddBnf9XujfMAlNn57DLOzy5qulDbBf0Q1y4ZI?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SolanahodlwhalesDAO",
        dao_id: "solanahodlwhales",
        num_nfts: 3000,
        image_url: "https://www.arweave.net/3042t147CbAFIugbPOEswO7vEBN05askQAYDyFu3a-M?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SuchshibasDAO",
        dao_id: "suchshibas",
        num_nfts: 10000,
        image_url: "https://www.arweave.net/aDrfmPYbxUm7j_bXNxxF1G8WBvFbrC7BsbxlheVns5k?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SoullessDAO",
        dao_id: "soulless",
        num_nfts: 9999,
        image_url: "https://www.arweave.net/gM4CKYco5VhLBFBTxveSpCQKRW1tXfhPW9FICIGwWtw?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "YakuengineeringDAO",
        dao_id: "yakuengineering",
        num_nfts: 6985,
        image_url: "https://arweave.net/QS84qE4p81fBB4YINfDOQxjYJ9-yImx6_Ki3sJ7FBnA",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "BoredapesolanaclubDAO",
        dao_id: "boredapesolanaclub",
        num_nfts: 6001,
        image_url: "https://testlaunchmynft.mypinata.cloud/ipfs/QmR4KDfrwvUyVcpxASCrNReEZmqXq4VpzwhJ1Tzy2K17b9/1789.png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "3dmouseDAO",
        dao_id: "3dmouse",
        num_nfts: 555,
        image_url: "https://www.arweave.net/avUUMgBS1h423Pkiw-vcFbkvmDBAszsPA_YlobP_o1I?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "MaushesclubDAO",
        dao_id: "maushesclub",
        num_nfts: 1111,
        image_url: "https://testlaunchmynft.mypinata.cloud/ipfs/QmNw4Ntn3aEx4NBdK3RvZC3Ygd1bdePDzPYYVhTWgBRvcy/657.png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "DiamondbaepeDAO",
        dao_id: "diamondbaepe",
        num_nfts: 2221,
        image_url: "https://arweave.net/Nm3KrSK4L9sxWICFPG5n8pPED8ntWyzbB267ZmltySo",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "MousefacenewSS()DAO",
        dao_id: "mousefacenewSS()",
        num_nfts: 184,
        image_url: "https://www.arweave.net/l8k-MgBaqE-2z2DhVKV8OkRWn5aekie2vWqA3MIJ2Bc?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "ToonwabbitsDAO",
        dao_id: "toonwabbits",
        num_nfts: 2221,
        image_url: "https://ipfs.io/ipfs/QmUoCmggAJiqvJbXGKvBVUAfVf8CJqj9ui3c562qX41mU2",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "NftreesolanaDAO",
        dao_id: "nftreesolana",
        num_nfts: 10000,
        image_url: "https://www.arweave.net/WQft_XIm-xg1HHhgLzL6bNnewSS()K3XlhKA0xBGcw2fbIqA?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "Boopiegen1NDAO",
        dao_id: "boopiegen1n",
        num_nfts: 2200,
        image_url: "https://www.arweave.net/D3cfvn1r_JNPbKlzpns0PM323rM4dYn-rnFbZvjk4CE?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "AstralhousesDAO",
        dao_id: "astralhouses",
        num_nfts: 4550,
        image_url: "https://arweave.net/d-MHka5l5-5ghKrMOMxYHpOkQ9aujZLIQePjPQiuBJs",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SolgodsDAO",
        dao_id: "solgods",
        num_nfts: 6666,
        image_url: "https://www.arweave.net/kqAmv87-sKN3Er8LiAjBQ_-OxundH5nI8Sc-Zoewx1s?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "PixeldrugsDAO",
        dao_id: "pixeldrugs",
        num_nfts: 176,
        image_url: "https://www.arweave.net/z0orlTF4502EEbsvu-rKXmJXrZZOguqpi2lRXQrH_8c?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "AngomonDAO",
        dao_id: "angomon",
        num_nfts: 3100,
        image_url: "https://www.arweave.net/NX55xvNN85MtuTUYWJvUyAj1K5Xj_f5ok-U9frsgf9Y?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "NftabsDAO",
        dao_id: "nftabs",
        num_nfts: 5200,
        image_url: "https://s3-eu-west-1.amazonaws.com/nftabs/production/mint_attempts/500/images/nft_164484569120220214-4-189qtym.webp?1644845694",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "AstralbabyapesDAO",
        dao_id: "astralbabyapes",
        num_nfts: 4500,
        image_url: "https://bafybeihurhlm5pfoubrvhib7rzln43b5aidremgkz4sgairxfsoucm4wyy.ipfs.dweb.link/718.png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "AngrybunnyclubDAO",
        dao_id: "angrybunnyclub",
        num_nfts: 5555,
        image_url: "https://www.arweave.net/sgxrQsGvvxgATMPw7h63dlSm1OXXPVQ0qcDxLI1mp3g?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "MunkhoagDAO",
        dao_id: "munkhoag",
        num_nfts: 4314,
        image_url: "https://www.arweave.net/59vED4iMBsaC1WmPd8yy7tm4QYKVcFlPk8BrXhCPdAs?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "MutantdinobeachclubDAO",
        dao_id: "mutantdinobeachclub",
        num_nfts: 4041,
        image_url: "https://www.arweave.net/S02ifwwHuSfbE5Aze0OR52SnBQYVTnPsgC-xKm7-3pI?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "ThesuitesnftDAO",
        dao_id: "thesuitesnft",
        num_nfts: 4932,
        image_url: "https://bafybeig4norc5leonf5ebmrfgwlltguia4jipnrpoks5wiup6koxqe7qoe.ipfs.dweb.link/0.jpg",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "PsyshroomsDAO",
        dao_id: "psyshrooms",
        num_nfts: 1839,
        image_url: "https://arweave.net/eLhEG8iThJFEeKAlePMtZoFWXi8AVGm8tTZLtm3LLAs",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SockpassDAO",
        dao_id: "sockpass",
        num_nfts: 8888,
        image_url: "https://arweave.net/bJK7GtnsItZxo35lNKMuBX5iNBC_t1J18i3N3PFZlKo?ext=gif",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "DegenlizzyDAO",
        dao_id: "degenlizzy",
        num_nfts: 4033,
        image_url: "https://www.arweave.net/qF52_DKlFI9kODrSkI1LJ4ygyUDYF44PTVwSXLckKH4?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "StarbotsgameDAO",
        dao_id: "starbotsgame",
        num_nfts: 6000,
        image_url: "https://bafybeid3lweoffeg47ik5dq6m3tdvuxvv4gyzroptvmbbk2ip4qforbq7y.ipfs.dweb.link/4539.png?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SkelliesDAO",
        dao_id: "skellies",
        num_nfts: 2083,
        image_url: "https://www.arweave.net/7K0O0TNTe6ECnPcETs5f76ypJMogFGwBzPUOcMeTlLk?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "ZillavskongDAO",
        dao_id: "zillavskong",
        num_nfts: 888,
        image_url: "https://www.arweave.net/UPFJSVTtDy0YMv1O2IGrPOEAXFhpPytopw92ud1Hs5g?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "MagicdaoDAO",
        dao_id: "magicdao",
        num_nfts: 23058,
        image_url: "https://bafybeihr7vi77syiup5o4avvzemhlp4v4nplpc23haderjcjkkzgah2a5u.ipfs.dweb.link/0.gif?ext=gif",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "BitbirdzDAO",
        dao_id: "bitbirdz",
        num_nfts: 1110,
        image_url: "https://www.arweave.net/gG8Y3zhMC_ZVOZivKJ-wbaZf_akeLVnU2aS3FPbamR0?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "CreepygirlDAO",
        dao_id: "creepygirl",
        num_nfts: 1101,
        image_url: "https://www.arweave.net/i-VyjcZJ2j5tjlaLBfkzJdftKRZM0bRmToV2tx7NdxQ?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "CitizensbysolsteadDAO",
        dao_id: "citizensbysolstead",
        num_nfts: 1357,
        image_url: "https://arweave.net/-zlXYjiW-pnxkIOaBLXcieSfFXmv1IpK_jZg0zdV4Yk",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SolanadquirrelDAO",
        dao_id: "solanadquirrel",
        num_nfts: 1110,
        image_url: "https://www.arweave.net/FC73sl6eoxmMorPXBKyrBdrWJVlI7PulCZxzPWQDqys?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "babyapesocialclubDAO",
        dao_id: "babyapesocialclub",
        num_nfts: 4999,
        image_url: "https://sld-babyapes.s3.amazonaws.com/164.png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "MetaforgeDAO",
        dao_id: "metaforge",
        num_nfts: 1687,
        image_url: "https://bafybeihpwraypmtt5fkxcqt42rv2v7fnxsfrypbx4g3barph4uretxzyoe.ipfs.dweb.link/1080.png?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "NiftynanasDAO",
        dao_id: "niftynanas",
        num_nfts: 7940,
        image_url: "https://www.arweave.net/lmuGKIAguB_sjVB62Ht4wiWXcQsnBvPuXNOlu98al0U?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "billionairebabymeerkatsclubDAO",
        dao_id: "billionairebabymeerkatsclub",
        num_nfts: 422,
        image_url: "https://arweave.net/8hpRsm5b1pfvTe4-65-bzwRXPavN6lPXZ1V5VyXcExU?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "ChickentribeDAO",
        dao_id: "chickentribe",
        num_nfts: 3415,
        image_url: "https://www.arweave.net/O2RC80Q_aY0aepkZjL9tk-751oNoHS-usZ-Ri_-kZjo?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "BoopiversethehistoriansDAO",
        dao_id: "boopiversethehistorians",
        num_nfts: 5500,
        image_url: "https://www.arweave.net/6lIrwlaXxz3Fqr7bpjXtejyvhdQsUp6RcZxD6UpvUlk?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "TheoctosDAO",
        dao_id: "theoctos",
        num_nfts: 4444,
        image_url: "https://arweave.net/-2aqm8Wg3sWWCnKbwL69l9pPpdvmMz3MZobsFgG77pA",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SaigowabbitsDAO",
        dao_id: "saigowabbits",
        num_nfts: 222,
        image_url: "https://arweave.net/7CsDBT5BQ6EN32uzWeYzOomwb4EYr7CJJek0YCYjyJ8",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "DokanapesDAO",
        dao_id: "dokanapes",
        num_nfts: 225,
        image_url: "https://www.arweave.net/QNEB96e9UZHfJcGPXDs7MD0K41x7cbJn9_4a74A8GdM?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SafariditionDAO",
        dao_id: "safaridition",
        num_nfts: 500,
        image_url: "https://www.arweave.net/vInXdL_cH2WLCJ5U9j3xOrbanWf7NgjQIk-a2zUsjyM?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "GeckosDAO",
        dao_id: "geckos",
        num_nfts: 10000,
        image_url: "https://www.arweave.net/_eexplgWlYSgZEd5C2CRCmbZuKmUoiCbOZXO6TuJ3fg?ext=jpeg",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "MagicpeachDAO",
        dao_id: "magicpeach",
        num_nfts: 4652,
        image_url: "https://arweave.net/SLVhnJHwtBbYR2IMgFPxUTXYXuuXsb1qRNcEAeP2p_E",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SolsocksDAO",
        dao_id: "solsocks",
        num_nfts: 500,
        image_url: "https://www.arweave.net/Ixe7Tx3ZG3De6XWN7Dhhg9mbUVxAFH2yooWKp6A8tSI?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "ElementartNFT2dDAO",
        dao_id: "elementartnft2d",
        num_nfts: 5000,
        image_url: "https://www.arweave.net/pTGGmckG3xDLPvDQCqDsswYChwYn5YaQF3Jd0Ta12CU?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "ProofofconsciousnessDAO",
        dao_id: "proofofconsciousness",
        num_nfts: 1150,
        image_url: "https://bafybeidv53cmppvlysydiyij3vateoltroihhdzovhhe6t7sn7ka3ywcja.ipfs.dweb.link/83.png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "PixelbandsDAO",
        dao_id: "pixelbands",
        num_nfts: 4444,
        image_url: "https://bafybeiftdoq6ybsxlualwdngcx3sbhyvzl4lqfhgrk7slu6w6sdvflyzry.ipfs.dweb.link/2523.gif",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "ThefellowshipDAO",
        dao_id: "thefellowship",
        num_nfts: 6543,
        image_url: "https://www.arweave.net/D0W5rzaFEQwwrM3Sw8M1gbXzfULRTWz6pNI52RgwpH0?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "MessagepartyDAO",
        dao_id: "messageparty",
        num_nfts: 5555,
        image_url: "https://bafybeig6e6nuwsiucg3mhikbvrfam4ga4s6dbelfyqkaykqvg5imundqae.ipfs.dweb.link/5049.png?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "BoryokudragonzDAO",
        dao_id: "boryokudragonz",
        num_nfts: 1112,
        image_url: "https://arweave.net/gSI-Hkrg96Ex0gKKgKk3JwvjwOh-kd6_IC1ylOtpYa8?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "BotheredottersDAO",
        dao_id: "botheredotters",
        num_nfts: 1855,
        image_url: "https://www.arweave.net/cM38YbOfLF6o4Esv8AxVUwjtgl7H2-6M_46dN0niHcs?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "RudegolemsDAO",
        dao_id: "rudegolems",
        num_nfts: 8888,
        image_url: "https://www.arweave.net/fmt_tv8aANPy1r_VG4kDEZiYKkg2uUaFik27HL8ehQI?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "AiirrelevantDAO",
        dao_id: "aiirrelevant",
        num_nfts: 1235,
        image_url: "https://www.arweave.net/mUIopYb5px-Urm4XdPkcd0SBxoLDUNN3HVYV-IHtd5s?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "DroniesDAO",
        dao_id: "dronies",
        num_nfts: 10000,
        image_url: "https://www.arweave.net/bfUB8er7v1m4XuxFp3aDYGUXx7wzHPYTn7sVSHOtsrE?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "PortalsDAO",
        dao_id: "portals",
        num_nfts: 5000,
        image_url: "https://arweave.net/QPsEEJ-YpRjF35LzHWGhuknJ0tdN7n0ehjxpvpwFYmE?ext=jpg",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "BestbudsDAO",
        dao_id: "bestbuds",
        num_nfts: 4200,
        image_url: "https://bafybeignvpjnqcrac7mt3o3kwtqmy4evwbambsw5rbd6jbzo44zbwqusfa.ipfs.dweb.link/461.png?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "SoldooglesDAO",
        dao_id: "soldoogles",
        num_nfts: 1111,
        image_url: "https://arweave.net/aIpTqqvbQEKk2JL5yQab-nqe1ya_YEghezM36fwhUNQ",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "CatalinawhilemixerDAO",
        dao_id: "catalinawhilemixer",
        num_nfts: 5555,
        image_url: "https://www.arweave.net/86yE0SsH0rCDf1iY5CYCtTnHwGW6j2fI9oQSuvi9dww?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "MechsofsolanaDAO",
        dao_id: "mechsofsolana",
        num_nfts: 8888,
        image_url: "https://www.arweave.net/LKS4QaW7HFSw_vj8-VlrTAayEJl1-PYFJb5g1wNZ7U0?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "Balloonsville2DAO",
        dao_id: "balloonsville2",
        num_nfts: 5000,
        image_url: "https://bafybeic67mds3vbyr3j4ax2fmo5psqdtbig746zqqegpv3y4im7ivq3tvm.ipfs.dweb.link/4856.png?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "JellybabiesDAO",
        dao_id: "jellybabies",
        num_nfts: 3333,
        image_url: "https://www.arweave.net/PLiLAm5ZalEQHqDRloEsdkfOGac3WOhUW-tRKEd45jw?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "AlpacalandDAO",
        dao_id: "alpacaland",
        num_nfts: 215,
        image_url: "https://www.arweave.net/emU6oLWIGXFWJIFWLbEjEcC0GSjupvYh6k8hvr67vxc?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "PinclubDAO",
        dao_id: "pinclub",
        num_nfts: 1136,
        image_url: "https://www.arweave.net/v4HnluWRjT6tXPxir8p_liVMqNwfgwlb2uJLOQMe-8k?ext=png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "RetrowolfDAO",
        dao_id: "retrowolf",
        num_nfts: 1111,
        image_url: "https://monkelabs.nyc3.digitaloceanspaces.com/retrowolves/assets/0b39de68df5d07f1a2929b9236680b0d.png",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "RudedemonsDAO",
        dao_id: "rudedemons",
        num_nfts: 2745,
        image_url: "https://arweave.net/w5TtEFEWc1vefbZ8VnrQgwZYkuaty5892XGXsqq37Ls",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "FancyfenchnftDAO",
        dao_id: "fancyfenchnft",
        num_nfts: 10000,
        image_url: "https://www.arweave.net/_eexplgWlYSgZEd5C2CRCmbZuKmUoiCbOZXO6TuJ3fg?ext=jpeg",
        is_member: false,
        address: undefined,
    },
    {
        display_name: "CybervillainzDAO",
        dao_id: "cybervillainz",
        num_nfts: 990,
        image_url: "https://www.arweave.net/HlSr-rT8ufgZ3kXWjQPKJ_4C0XuoxZyFZX2st9ttqYc?ext=png",
        is_member: false,
        address: undefined,
    }
];

export {verifiedDaos};
